### ISSUE TITLE
Tag completion difficulties

### ISSUE THREAD

**Issue by Bruce-Connor** [vermiculus/sx.el#137]
I'm writing up tag completion, and I noticed a pretty big obstacle.

I originally thought we could just get a list of all tags upon first entering `compose-mode`, and then offer completion on that. However, queries are limited to return 100 items, and SO has almost 40,000 tags.
Obviously doing 400 requests is absolutely unnacceptable.

Here's what I'm thinking of doing now:

As the user is typing up a tags, fetch a list of the top 100 tags (a single query) matching the string typed so far, and offer those as completion. This implies one API request each time a completion menu is displayed.

That should be a lot better than 400, but on sites with fewer tags (emacs.SE has only a few hundred) this will be a lot less efficient than just getting all tags from the start.

**Comment by Bruce-Connor** [comment]
Alright, now that the bot is done, we can start doing tag completion.
As per gitter discussion, we'll start with `completing-read`.

I'll write a command that reads from the minibuffer and inserts a tag.

**Comment by vermiculus** [comment]
Just as a note, it doesn't take 4500 requests to do this. Actual implementation tests reveal it takes around 1450.
