### ISSUE TITLE
Question Data on browse

### ISSUE THREAD

**Issue by vermiculus** [vermiculus/sx.el#15]
It would be really nifty to display different types of data in the modeline (or somehow have access to it) as the user browses with `n`/`p`.  Things like bounty, etc.

**Comment by Bruce-Connor** [comment]
I've ben thinking about this issue. I think all of this information can be displayed directly on the list.

- The bounty can go under the vote count or the answer count (the start of the second line). 
- The user information can go after the tags.

Do you agree? If so, I'll implement that and we can close this.

**Comment by vermiculus** [comment]
Sounds good. If possible though, the user information should be somehow aligned vertically.

**Comment by Bruce-Connor** [comment]
Good idea. I'll see how I can do that.
Should I right-align it as well? Or left-align?

**Comment by vermiculus** [comment]
Whichever you think is best. There's a definite trade-off whichever you do:
- right-align and draw attention to names
- left-align and draw attention to reputation

It could potentially go on its own line as well, but I think that's bordering *really* fat question cells in the table.
