### ISSUE TITLE
Emacs seems to get stuck trying to fetch sx-tab-

### ISSUE THREAD

**Issue by kaushalmodi** [vermiculus/sx.el#152]
When try launching any sx tab like `M-x sx-tab-frontpage`, I get the below and then nothing happens.
I need to hit `C-g` to cancel whatever is happening in the background.

I have tried waiting for a minute or two but the SX Frontpage does not open.

<pre>
Contacting host: api.stackexchange.com:443
Opening TLS connection to `api.stackexchange.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 api.stackexchange.com'...done
Opening TLS connection to `api.stackexchange.com'...done
</pre>

The same thing happens will other sx-tab- commands I tried too.

I reran `M-x sx-authenticate` and that step works fine.

**Comment by kaushalmodi** [comment]
Finally got this working! The gnutls library was at version 1.4.1 earlier. Updating that to version 3.0.32 fixed this problem.

**Comment by Bruce-Connor** [comment]
Great!
