### ISSUE TITLE
Hiding questions doesn't work

### ISSUE THREAD

**Issue by Bruce-Connor** [vermiculus/sx.el#180]
After marking a few questions as hidden, previous ones get unhidden.

The contents of my `.sx/hidden-questions.el` cache are also clearly wrong:

    (("emacs" 3658) ("emacs" 3658 5786) ("emacs" 3658 5786) ("emacs" 3658 5703) ("emacs" 5418 5703) ("emacs" 5418))

probably something in `sx-question--mark-hidden` or `sx-question--ensure-hidden-list`.

**Comment by vermiculus** [comment]
This is fixed now, yes?

**Comment by Bruce-Connor** [comment]
Weird. This should have been closed by github when we merged #181
