### ISSUE TITLE
Use defconst for filters 

### ISSUE THREAD

**Issue by Bruce-Connor** [vermiculus/sx.el#200]
We should be using defconst instead of defvar on all filters (and on anything else that's constant, for that matter). 

defconst is reevaluated when the package is upgraded, but defvar isn't. And since the filters are constantly being updated by PRs, we'll run into problems if the user runs one of our functions after upgrading the package.

**Comment by vermiculus** [comment]
Yes, absolutely.

**Comment by Bruce-Connor** [comment]
I can do this now. Should I build it off `master` or `organize`?

**Comment by Bruce-Connor** [comment]
Nevermind, I see you merged it/ :)
