### ISSUE TITLE
Error on any sx-tab-* when you aren't authenticated

### ISSUE THREAD

**Issue by areina** [vermiculus/sx.el#205]
With current master, not authenticated, I'm trying to do `M-x sx-tab-frontpage` emacs and I get this error:
```
sx-method-call: Wrong number of arguments: ((t) (_method &optional _args _request-method) "Fallback method when authentication is not available.
This is for UI generation when the associated API call would
require authentication.
Currently returns nil." (quote (nil))), 4
```

**Comment by Bruce-Connor** [comment]
Thanks for submitting. I think I know the problem. We'll try to get to this today.

**Comment by vermiculus** [comment]
From Gitter, this is probably due to the request fallback function. I failed to update it when I introduced `process-function` as an argument in #187

**Comment by vermiculus** [comment]
@areina Can you verify that this fixes the present issue? Note that SX does not currently work without authentication, but the `Wrong number of arguments` error should be fixed.

**Comment by areina** [comment]
Yup, it's working! thank you
