### ISSUE TITLE
missing? data gives errors

### ISSUE THREAD

**Issue by csrhodes** [vermiculus/sx.el#206]
Hi,

I don't know if I'm doing something wrong, or if someone else is, but: I saw sx on MELPA and thought I'd give it a try (MELPA version 20150105.1006, Emacs 24.4.1 on Debian); I get errors when trying to display question lists and individual questions.  In `sx-question-list--print-info`, I found I needed to guard `(number-to-string .reputation)` with a check to see if `.reputation` was actually present; similarly, in `sx-question-mode--print-section` I found an unset `.creation_date`, again needing a guard before calling `sx-time-seconds-to-date`.

I haven't really probed further, and can't immediately in any case: are these known problems, problems that arise from API changes, or some kind of misconfiguration at my end?  They occurred for me both unauthenticated and after authentication.

Thanks,

Christophe

**Comment by vermiculus** [comment]
Can you link to the site you were trying to view? Was it StackOverflow or some other site on the network? We recently added support for displaying reputation, etc. in the question list, so it may be a little wonky. (We don't always know all of the possible responses we can get.) It seems odd that `.creation_date` would be unset, though -- I can't think of an instance where that would be the case. Do you have any idea which question was trying to be displayed?

@Bruce-Connor -- do you have any idea how he could get this information? My immediate thought is debug-on-error and try to eval one of the `.variable` letbindings, but I don't know if that's possible and won't be able to test for several hours.

**Comment by csrhodes** [comment]
I saw this on (not just one of) the StackExchange sites (e.g. emacs.stackexchange.com).  Going by the stack trace after `toggle-debug-on-error` shows an alist with `creation_date` just plain missing.

Not sure how to help debug this, I'm afraid

**Comment by vermiculus** [comment]
Might this be related to #202? Try restarting emacs entirely.

**Comment by csrhodes** [comment]
Sadly, no change.  (This is the first and only version of sx.el that I've had on the system)

**Comment by vermiculus** [comment]
Hmmm... I'll have to take a look when I get home, but thanks for reporting!

**Comment by Bruce-Connor** [comment]
Two quick questions:

- Does this happen if you do sx-tab-frontpage and choose the emacs site right now? (I'm asking so I can try to reproduce this) 
- Are you authenticated?

**Comment by csrhodes** [comment]
Right now, the front page of the emacs SE does not trigger an error, but attempting to view a question does (after RET on the first question, I get `wrong type argument: number-or-marker-p, nil`).  I ran this test twice, each in a fresh emacs session, once authenticated and once not, with the same results.

**Comment by Bruce-Connor** [comment]
Ok, I think there are two errors at play here.
First, we forgot to specify creation_date in the filters (which makes me wonder how it even worked on my machine). 
Second, the [shallow_user](https://api.stackexchange.com/docs/types/shallow-user) might indeed not provide a reputation (even though we do specify it). I have no idea why that's the case, but it is.

I'll fix both in a moment.

**Comment by Bruce-Connor** [comment]
The fix should be on Melpa anytime now. Github autoclosed this, but please let us know if you still have the error!

Cheers
