### ISSUE TITLE
Standardize display of user names

### ISSUE THREAD

**Issue by Bruce-Connor** [vermiculus/sx.el#208]
User names are displayed both on the question list and on the question buffer now. 
Would be good to have a function to convert the `user` object into a string, and use it on both places.

**Comment by vermiculus** [comment]
Definitely agree. Would it be good to have one cl-defun to specify which fields to include? Or perhaps a normal defun that takes some symbol (`'name) or property (`:name`) and returns the string representation?

**Comment by Bruce-Connor** [comment]
I think a cl-defun is OK. But right now we only have name and rep, so those two can probably be included by default.

**Comment by Bruce-Connor** [comment]
I ended up doing something very different. The function takes two arguments a format string and a user object. I'm quite happy of how it turned out. :-)

**Comment by vermiculus** [comment]
I like it :+1:

**Comment by Bruce-Connor** [comment]
I think I should have closed this with #216
