### ISSUE TITLE
Add "-" to allowed chars in raw links.

### ISSUE THREAD

**Issue by Bruce-Connor** [vermiculus/sx.el#227]

**Comment by Bruce-Connor** [comment]
see http://emacs.stackexchange.com/q/7371/50

**Comment by vermiculus** [comment]
Is that the right link?

**Comment by Bruce-Connor** [comment]
Yes. The question has a raw link. You need to click on `edit` to see it, because the website auto-renders raw links to other questions.

**Comment by Bruce-Connor** [comment]
> This is more or less a question of putting the answer from http://emacs.stackexchange.com/questions/2355/make-web-mode-always-indent-with-spaces into the `use-package` declaration.

**Comment by vermiculus** [comment]
Ooh -- you're talking about question printing. I thought you were talking about the visit-from-link function.

**Comment by Bruce-Connor** [comment]
Oh yes, sorry. I'm talking about linkifying the question buffer.

**Comment by vermiculus** [comment]
I don't think it would be a bad idea to 'shorten' the link as well and put the full url in the `help-echo`.

**Comment by Bruce-Connor** [comment]
Agreed.
