### ISSUE TITLE
Sending answer causes wrong-type-argument error

### ISSUE THREAD

**Issue by lunaryorn** [vermiculus/sx.el#238]
When pressing `C-c C-c` in a compose buffer for an answer, a `wrong-type-argument` error gets signalled, in a call `sx-question-mode--fill-and-fontify(nil)`, from `sx-question-mode--print-section`.

I have a complete backtrace for the error, but I'm not sure whether it might contain any private data, e.g. auth tokens or whatever, so I'd prefer to send it privately to you.  Do you have any contact address for this sort of communication?

**Comment by Bruce-Connor** [comment]
You can find my email on my github profile. Send it to me there. 
I suspect this is yet another case of the api returning incomplete objects. 

In any case, this almost certainly happens after posting the answer. Could you check that the answer was posted correctly despite the error?

**Comment by lunaryorn** [comment]
@Bruce-Connor The answer was posted correctly, sorry, forgot to say that in the OP.

I send the traceback to your mail address.

**Comment by Bruce-Connor** [comment]
Ok. I've managed to reproduce this consistently. 

It is definitely a case of the API returning bad objects, namely answers without bodies (I feel like we're walking on egg shells with this thing). I'll add some dirty patch for now, then I'll try to figure out which commit caused this, so that maybe we can workaround this.

**Comment by vermiculus** [comment]
See also http://emacs.stackexchange.com/q/7545/2264.

**Comment by Bruce-Connor** [comment]
Ok, the permanent solution for this general set of problems is very much still under work. 
For now I've fixed our call to `with-demoted-error`, which means that when the user posts an answer the error message is clearer and less aggressive and it doesn't halt execution of the `after-send-functions` hook.

This means that the window/buffer will close/kill correctly, and user won't be under the impression that the answer wasn't posted.
