### ISSUE TITLE
Wrong type argument: listp, \.\.\. when trying to view a question [emacs 24.4]

### ISSUE THREAD

**Issue by kaushalmodi** [vermiculus/sx.el#244]
Hi, 
On emacs 24.4. and the Jan 26 version of sx.el, I get this error `Wrong type argument: listp, \.\.\.` when trying to view a question.

The sx-* tabs open fine.

<pre>
Debugger entered--Lisp error: (wrong-type-argument listp \.\.\.)
  car(\.\.\.)
  (> (car x) (car y))
  (lambda (x y) (> (car x) (car y)))((7747 . 1422444620) \.\.\.)
  (and (cdr-safe tail) ((lambda (x y) (> (car x) (car y))) x (cadr tail)))
  (while (and (cdr-safe tail) ((lambda (x y) (> (car x) (car y))) x (cadr tail))) (setq tail (cdr tail)))
  (let ((tail site-cell) (x q-cell)) (while (and (cdr-safe tail) ((lambda (x y) (> (car x) (car y))) x (cadr tail))) (setq tail (cdr tail))) (setcdr tail (cons x (cdr tail))))
  (cond ((null site-cell) (setq sx-question--user-read-list (cons (list \.site_par q-cell) sx-question--user-read-list))) ((setq cell (assoc \.question_id site-cell)) (if (or (not (numberp (cdr cell))) (> \.last_activity_date (cdr cell))) (progn (setcdr cell \.last_activity_date)))) (t (let ((tail site-cell) (x q-cell)) (while (and (cdr-safe tail) ((lambda (x y) (> ... ...)) x (cadr tail))) (setq tail (cdr tail))) (setcdr tail (cons x (cdr tail))))))
  (let ((site-cell (assoc \.site_par sx-question--user-read-list)) (q-cell (cons \.question_id \.last_activity_date)) cell) (cond ((null site-cell) (setq sx-question--user-read-list (cons (list \.site_par q-cell) sx-question--user-read-list))) ((setq cell (assoc \.question_id site-cell)) (if (or (not (numberp (cdr cell))) (> \.last_activity_date (cdr cell))) (progn (setcdr cell \.last_activity_date)))) (t (let ((tail site-cell) (x q-cell)) (while (and (cdr-safe tail) ((lambda ... ...) x (cadr tail))) (setq tail (cdr tail))) (setcdr tail (cons x (cdr tail)))))))
  (let ((\.site_par (cdr (assq (quote site_par) alist))) (\.question_id (cdr (assq (quote question_id) alist))) (\.last_activity_date (cdr (assq (quote last_activity_date) alist)))) (sx-question--ensure-read-list \.site_par) (let ((site-cell (assoc \.site_par sx-question--user-read-list)) (q-cell (cons \.question_id \.last_activity_date)) cell) (cond ((null site-cell) (setq sx-question--user-read-list (cons (list \.site_par q-cell) sx-question--user-read-list))) ((setq cell (assoc \.question_id site-cell)) (if (or (not (numberp ...)) (> \.last_activity_date (cdr cell))) (progn (setcdr cell \.last_activity_date)))) (t (let ((tail site-cell) (x q-cell)) (while (and (cdr-safe tail) (... x ...)) (setq tail (cdr tail))) (setcdr tail (cons x (cdr tail))))))))
  (let ((alist question)) (let ((\.site_par (cdr (assq (quote site_par) alist))) (\.question_id (cdr (assq (quote question_id) alist))) (\.last_activity_date (cdr (assq (quote last_activity_date) alist)))) (sx-question--ensure-read-list \.site_par) (let ((site-cell (assoc \.site_par sx-question--user-read-list)) (q-cell (cons \.question_id \.last_activity_date)) cell) (cond ((null site-cell) (setq sx-question--user-read-list (cons (list \.site_par q-cell) sx-question--user-read-list))) ((setq cell (assoc \.question_id site-cell)) (if (or (not ...) (> \.last_activity_date ...)) (progn (setcdr cell \.last_activity_date)))) (t (let ((tail site-cell) (x q-cell)) (while (and ... ...) (setq tail ...)) (setcdr tail (cons x ...))))))))
  (progn (sx--ensure-site question) (let ((alist question)) (let ((\.site_par (cdr (assq (quote site_par) alist))) (\.question_id (cdr (assq (quote question_id) alist))) (\.last_activity_date (cdr (assq (quote last_activity_date) alist)))) (sx-question--ensure-read-list \.site_par) (let ((site-cell (assoc \.site_par sx-question--user-read-list)) (q-cell (cons \.question_id \.last_activity_date)) cell) (cond ((null site-cell) (setq sx-question--user-read-list (cons ... sx-question--user-read-list))) ((setq cell (assoc \.question_id site-cell)) (if (or ... ...) (progn ...))) (t (let (... ...) (while ... ...) (setcdr tail ...))))))))
  (prog1 (progn (sx--ensure-site question) (let ((alist question)) (let ((\.site_par (cdr (assq ... alist))) (\.question_id (cdr (assq ... alist))) (\.last_activity_date (cdr (assq ... alist)))) (sx-question--ensure-read-list \.site_par) (let ((site-cell (assoc \.site_par sx-question--user-read-list)) (q-cell (cons \.question_id \.last_activity_date)) cell) (cond ((null site-cell) (setq sx-question--user-read-list ...)) ((setq cell ...) (if ... ...)) (t (let ... ... ...))))))) (sx-cache-set (quote read-questions) sx-question--user-read-list))
  sx-question--mark-read(((title . "How does package.el handle changes in macros when updating?") (site_par . "emacs") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating") (body_markdown . "Let's assume there is a package `P` containing two files,\n\n      P/base.el\n      P/utils.el\n\n, where the `base.el` file requires `utils.el` at runtime and `utils.el` contains a macro `M`. Upon first installation of `P`, package.el downloads, extracts and compiles it.\n\nNow assume the package maintainer updated `P` to `P'` and in the process modified `M` to `M'`.  The package user now attempts to update his package via package-list. Since `P` is a useful package, it is also loaded.  Again package.el downloads and extracts `P'`.  But I don't see how the code from the updated macro `M'` gets into the compiled file `P'/base.el`, since the feature `utils.el` is already provided, so, I assume, and the compiler is happy to use the old definition `M`.\n\nThe question I have about this is simply whether this is a correct analysis ?\n\n\n\n") (share_link . "http://emacs.stackexchange.com/q/7747/115") (question_id . 7747) (last_edit_date . 1422421325) (creation_date . 1422394782) (last_activity_date . 1422444620) (score . 3) (answer_count . 1) (accepted_answer_id . 7751) (view_count . 33) (is_answered . t) (upvoted . :json-false) (downvoted . :json-false) (last_editor (link . "http://emacs.stackexchange.com/users/5253/politza") (display_name . "politza") (profile_image . "https://www.gravatar.com/avatar/76377bf8146d0a242d8fcb05ecd40626?s=128&d=identicon&r=PG&f=1") (user_type . "registered") (user_id . 5253) (reputation . 173)) (comments . [((body . "Not hundred percent sure, but there's a good chance that <code>(require 'package)</code> will actually re-load and re-evaluate the package if the file is newer. So the macro definition is likely to be updated. However, the places where expansion already happened will not be updated.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating#comment11621_7747") (body_markdown . "Not hundred percent sure, but there's a good chance that `(require 'package)` will actually re-load and re-evaluate the package if the file is newer. So the macro definition is likely to be updated. However, the places where expansion already happened will not be updated.") (comment_id . 11621) (post_id . 7747) (creation_date . 1422396205) (post_type . "question") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner (link . "http://emacs.stackexchange.com/users/563/wvxvw") (display_name . "wvxvw") (profile_image . "https://www.gravatar.com/avatar/e5ab5db401198485d4569199f9994a7d?s=128&d=identicon&r=PG") (accept_rate . 73) (user_type . "registered") (user_id . 563) (reputation . 1297))) ((body . "FYI, it doesn't look to me as if <code>require</code> (at least as at 24.4.1) performs any such check. If the feature was registered as having been loaded, I believe that's all that matters.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating#comment11625_7747") (body_markdown . "FYI, it doesn't look to me as if `require` (at least as at 24.4.1) performs any such check. If the feature was registered as having been loaded, I believe that's all that matters.") (comment_id . 11625) (post_id . 7747) (creation_date . 1422404511) (post_type . "question") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner (link . "http://emacs.stackexchange.com/users/454/phils") (display_name . "phils") (profile_image . "https://www.gravatar.com/avatar/3b1ad4e4bdf8feaef18504593914fe16?s=128&d=identicon&r=PG") (user_type . "registered") (user_id . 454) (reputation . 3911))) ((body . "Obviously, explicitly <code>load</code>ing the recompiled library would resolve the issue, and it's certainly possible that the package manager does exactly that after updating libraries which were previously loaded.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating#comment11626_7747") (body_markdown . "Obviously, explicitly `load`ing the recompiled library would resolve the issue, and it's certainly possible that the package manager does exactly that after updating libraries which were previously loaded.") (comment_id . 11626) (post_id . 7747) (creation_date . 1422404742) (post_type . "question") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner (link . "http://emacs.stackexchange.com/users/454/phils") (display_name . "phils") (profile_image . "https://www.gravatar.com/avatar/3b1ad4e4bdf8feaef18504593914fe16?s=128&d=identicon&r=PG") (user_type . "registered") (user_id . 454) (reputation . 3911))) ((body . "@phils It doesn't do that on 24.4, but does in 25.1. Explicitly loading the file in your package is indeed a workaround.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating#comment11627_7747") (body_markdown . "@phils It doesn't do that on 24.4, but does in 25.1. Explicitly loading the file in your package is indeed a workaround.") (comment_id . 11627) (post_id . 7747) (creation_date . 1422408758) (post_type . "question") (score . 1) (edited . :json-false) (upvoted . :json-false) (reply_to_user (link . "http://emacs.stackexchange.com/users/454/phils") (display_name . "phils") (profile_image . "https://www.gravatar.com/avatar/3b1ad4e4bdf8feaef18504593914fe16?s=128&d=identicon&r=PG") (user_type . "registered") (user_id . 454) (reputation . 3911)) (owner (link . "http://emacs.stackexchange.com/users/50/malabarba") (display_name . "Malabarba") (profile_image . "https://www.gravatar.com/avatar/c14505947446e90f2a14fd8f3dd3cf94?s=128&d=identicon&r=PG") (accept_rate . 84) (user_type . "moderator") (user_id . 50) (reputation . 8110)))]) (owner (link . "http://emacs.stackexchange.com/users/5253/politza") (display_name . "politza") (profile_image . "https://www.gravatar.com/avatar/76377bf8146d0a242d8fcb05ecd40626?s=128&d=identicon&r=PG&f=1") (user_type . "registered") (user_id . 5253) (reputation . 173)) (tags . ["elisp" "package"]) (answers . [((link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#7751") (body_markdown . "> But I don't see how the code from the updated macro M' gets into the compiled file P'/base.el, since the feature utils.el is already provided, [...]\n\nIt doesn't. Or, actually, it **didn't**.\n\n## The bug ##\n\nYour analysis is correct. \nIt was [a bug](https://lists.gnu.org/archive/html/emacs-devel/2014-10/msg00567.html) in `package.el`, and it's [been fixed](https://lists.gnu.org/archive/html/emacs-diffs/2014-12/msg00254.html) on [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c13baa10d55ec863d3ceaea48c6b2959ece98198) for the next Emacs release. As of\nthe next version, when `package.el` upgrades a package that has been\nloaded in this session, it will reload a package after installing it.\n\n## The workaround ##\n\nOne workaround is to `load` a package instead of `require`ing it.\nThough this is bad style, I would consider it an acceptable\ncompromise, if you *know* you'll be affected by this.  \nYou know you'll be affected by this if your package is about to make\nuse of a newly released feature of a pre-existing macro that's on another file (or another package).\n") (share_link . "http://emacs.stackexchange.com/a/7751/115") (question_id . 7747) (answer_id . 7751) (creation_date . 1422408152) (last_edit_date . 1422444620) (last_activity_date . 1422444620) (score . 2) (is_accepted . t) (upvoted . :json-false) (downvoted . :json-false) (last_editor (link . "http://emacs.stackexchange.com/users/50/malabarba") (display_name . "Malabarba") (profile_image . "https://www.gravatar.com/avatar/c14505947446e90f2a14fd8f3dd3cf94?s=128&d=identicon&r=PG") (accept_rate . 84) (user_type . "moderator") (user_id . 50) (reputation . 8110)) (comments . [((body . "<a href=\"http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c13baa10d55ec863d3ceaea48c6b2959ece98198\" rel=\"nofollow\">This</a> looks like the relevant commit.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#comment11649_7751") (body_markdown . "[This](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c13baa10d55ec863d3ceaea48c6b2959ece98198)\nlooks like the relevant commit.") (comment_id . 11649) (post_id . 7751) (creation_date . 1422444486) (post_type . "answer") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner ... ... ... ... ... ...)) ((body . "@politza yes, thanks.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#comment11650_7751") (body_markdown . "@politza yes, thanks.") (comment_id . 11650) (post_id . 7751) (creation_date . 1422444694) (post_type . "answer") (score . 0) (edited . :json-false) (upvoted . :json-false) (reply_to_user ... ... ... ... ... ...) (owner ... ... ... ... ... ... ...)) ((body . "Though, I think it's still broken, since the reloading happens <i>after</i> the package was compiled (with the old macros).") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#comment11653_7751") (body_markdown . "Though, I think it's still broken, since the reloading happens *after*\nthe package was compiled (with the old macros).") (comment_id . 11653) (post_id . 7751) (creation_date . 1422446894) (post_type . "answer") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner ... ... ... ... ... ...)) ((body . "@politza oh yes. I misinterpreted the question (I'll update the answer later) . This was fixed for macros from another package. It still needs work for macros inside the same package that are on a different file. Fortunately, the <code>load</code> instead of <code>require</code> workaround still works for that situation, and it's kind of a no brainer there.") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#comment11654_7751") (body_markdown . "@politza oh yes. I misinterpreted the question (I'll update the answer later) . This was fixed for macros from another package. It still needs work for macros inside the same package that are on a different file. Fortunately, the `load` instead of `require` workaround still works for that situation, and it's kind of a no brainer there.") (comment_id . 11654) (post_id . 7751) (creation_date . 1422447371) (post_type . "answer") (score . 0) (edited . :json-false) (upvoted . :json-false) (reply_to_user ... ... ... ... ... ...) (owner ... ... ... ... ... ... ...)) ((body . "And it's still listed as <a href=\"http://debbugs.gnu.org/cgi/bugreport.cgi?bug=10125\" rel=\"nofollow\">bug #10125</a>. I should have checked there first, but the assumed implication of hundreds of broken packages out there kept me from doing so...") (link . "http://emacs.stackexchange.com/questions/7747/how-does-package-el-handle-changes-in-macros-when-updating/7751#comment11655_7751") (body_markdown . "And it's still listed as [bug\n#10125](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=10125). I should\nhave checked there first, but the assumed implication of hundreds of\nbroken packages out there kept me from doing so...") (comment_id . 11655) (post_id . 7751) (creation_date . 1422447475) (post_type . "answer") (score . 0) (edited . :json-false) (upvoted . :json-false) (owner ... ... ... ... ... ...))]) (owner (link . "http://emacs.stackexchange.com/users/50/malabarba") (display_name . "Malabarba") (profile_image . "https://www.gravatar.com/avatar/c14505947446e90f2a14fd8f3dd3cf94?s=128&d=identicon&r=PG") (accept_rate . 84) (user_type . "moderator") (user_id . 50) (reputation . 8110)))])))
</pre>

**Comment by vermiculus** [comment]
Do you know which question you were trying to view? You can use either `w` or `v` to get the link for the question from the question list.

**Comment by kaushalmodi** [comment]
From the debugger log above, I was trying to view: "How does package.el handle changes in macros when updating?" question. 

This problem is not specific to any question.. it happens with all questions.

**Comment by kaushalmodi** [comment]
On pressing `v` the correct question opens in the web browser but I still get that listp problem.

**Comment by kaushalmodi** [comment]
Found the problem.

I need to set emacs version specific `url/` folders. I have separate `elpa/` folders but that is not enough. The problem got resolved once I deleted the `url/` folder and all files in `.sx/` except for `auth.el`.

**Comment by vermiculus** [comment]
Alright. I still don't understand what went wrong, but I guess that's ok.

Am I to understand that you have separate ELPA directories for each installed version of emacs? Would I be correct in assuming this problem would not occur if this were not the case?

On a side note, I really want to find the sadistic developer who wrote `url.el` – it's caused us a lot of problems as of late.

**Comment by kaushalmodi** [comment]
Nope, the problem occurred because the files in `url/` and/or `.sx/` were created differently by emacs 25.0.50.1 and 24.4. So when I tried to read the sx question in emacs 24.4, the cache or some other files in one of the above 2 directories that were written using the 25.0.50.1 emacs libraries were in some format incompatible with emacs 24.4.

I am starting to put these in my init:

<pre>
(setq emacs-version-short  (replace-regexp-in-string
                            "\\([0-9]+\\)\\.\\([0-9]+\\).*"
                            "\\1_\\2" emacs-version)) ; 25.0.50.1 -> 25_0
(setq url-configuration-directory (locate-user-emacs-file
                                   (concat "url_"
                                           emacs-version-short
                                           "/") "url/"))
</pre>

**Comment by Bruce-Connor** [comment]
This was not a problem with url. If I'm reading this backtrace correctly, there was an invalid entry in your sx cache (it was a `...` symbol). That's why deleting the cache solved it. 

What worries me is how it got there. Emacs versions probably have nothing to do with it, but I have absolutely no idea how that symbol got into the cache.

**Comment by vermiculus** [comment]
Is it possibly an issue with `princ` (or whatever we're using)? Perhaps the data structure is deeper than the printing defaults.

**Comment by Bruce-Connor** [comment]
Oh yes!!! Certainly.

**Comment by Bruce-Connor** [comment]
Is that something we've fixed already? Otherwise it seems pretty urgent. :-)

**Comment by kaushalmodi** [comment]
@vermiculus @Bruce-Connor Are you guys having trouble executing `gist-list` command from the [`gist`](https://github.com/defunkt/gist.el) package. I am having trouble running any gist-* command and I see the ellipsis in the debug log. As I thought these issues could be related.. I have referenced this issue in the `gh.el` github issue manager: https://github.com/sigma/gh.el/issues/44

**Comment by Bruce-Connor** [comment]
@kaushalmodi Is the ellipsis written as `...` or `\.\.\.`?
The former is OK, the debug log is probably just being truncated. 
The latter is a problem, it is actually a symbol which is an ellipsis.

**Comment by kaushalmodi** [comment]
Oh well, it is written as `...` :(
