### ISSUE TITLE
Search without query fails

### ISSUE THREAD

**Issue by cocreature** [vermiculus/sx.el#249]
When I start a search using `C-u S` and then use stackoverflow as the site, no query and haskell as tags I get the following error
```
Debugger entered--Lisp error: (wrong-type-argument stringp ("haskell"))
  byte-code("\301!\302\303\304\203
  call-interactively(sx-search nil nil)
  command-execute(sx-search)
```
When I insert a query it seems to work fine. Not quite sure what's going on here.

**Comment by Bruce-Connor** [comment]
I can confirm I've run into this before. I'll try look into it during the weekend.

**Comment by Bruce-Connor** [comment]
Should be fixed on latest version.
Let us know if it works!
