### ISSUE TITLE
install error from melpa

### ISSUE THREAD

**Issue by cedricpinson** [vermiculus/sx.el#255]
url-insert-file-contents: http://melpa.milkbox.net/packages/sx-20150203.1831.tar: Not found

**Comment by vermiculus** [comment]
As a general rule, bug reports need stack traces :) From what I can tell, we aren't calling `url-insert-file-contents` at all. Where are you receiving this error? (It may even be a (possibly temporary) MELPA bug.)

**Comment by cedricpinson** [comment]
ok thx for the answer I installed the previous version instead. I am using emacs24.4 and also the command sx-search says it's undefined.
How can I give you more useful informations ?

**Comment by cocreature** [comment]
You need to `(require 'sx-search)`.

**Comment by cedricpinson** [comment]
thx, I close it, sorry I guess I could have find this myself

**Comment by Bruce-Connor** [comment]
This is actually a bug. sx-search should be autoloaded. :-)

**Comment by Bruce-Connor** [comment]
As for the download thing. It probably happened that between the time you refreshed your package list and the time you asked to install sx, Melpa built and released a new version of sx, so the old one wasn't available anymore.

You should try installing the latest version, and if installation itself fails (with that same message) it might be good to file an issue on Melpa.
