### ISSUE TITLE
lack of authentication breaks "draft question" after authentication resolved

### ISSUE THREAD

**Issue by peterbecich** [vermiculus/sx.el#271]
I tried to ask a question without authenticating beforehand.  "Finish and send" directed me to authenticate, which worked fine.  Sometime between this failed "ask" and successful authentication, though, the header disappeared on the unasked question.  Trying to "Finish and send" or re-insert a tag gives error "No tags header found".  Easy to work around by just asking a new question, of course.

```
C-c C-c: Finish and Send    C-c C-q: Insert tags    C-c C-k: Discard Draft

How do you limit ENSIME's typechecking to one SBT subproject?  The project contains code duplicated by multiple subprojects,
```

sx version 20150302.1409 and Emacs version 24.4.1

**Comment by Malabarba** [comment]
Forgot to comment here due to github's automated closing, but this should now be fixed.
