### ISSUE TITLE
How could I 'Accept' an answer?

### ISSUE THREAD

**Issue by enzochiau** [vermiculus/sx.el#276]
Can I 'Accept' an answer for my question?

**Comment by vermiculus** [comment]
It doesn't appear that you can, at the moment :) Presumably, neither Artur nor I have needed to yet.

**Comment by Malabarba** [comment]
Yes, I'll admit that's the biggest missing feature right now. Frankly, it would be trivial to implement if anyone wants to give it a try.

It should go in sx-interaction.el, and it should be very similar to the voting commands.

I'm on holiday at the moment, but I can do it later if no-one else does

**Comment by Malabarba** [comment]
There's now a button to accept answers. 
Let us know if it works!

**Comment by shackra** [comment]
Maybe I'm using an old version of sx.el but I don't see such button, neither the shortcut key. I'm using `sx 20150718.625` from Melpa.
