### ISSUE TITLE
sx-search.el not getting loaded

### ISSUE THREAD

**Issue by kaushalmodi** [vermiculus/sx.el#277]
When I click on any tag in an sx tab (*All-Questions* tab, for example), I got the error

> button-activate: Symbol's function definition is void: sx-search-tag-at-point

But I grepped `sx` source and saw that `sx-search-tag-at-point` definition actually existed.

So I opened `sx-search.el` and `eval`ed it manually and then the "jump to tag by clicking on tag" started working.

So I believe that that function needs to be loaded automatically or `sx-search` needs to be required at the right time.

**Comment by Malabarba** [comment]
Thanks for catching that. 
For now, I'll fix this by autoloading `sx-search-tag-at-point`.

This package is very liberal on its separation of files (we have 28 `.el`s!). That was definitely an experiment worth doing, but this sort of issue shows we may have missed the spot a little bit.

**Comment by peterbecich** [comment]
I get ```execute-extended-command: Cannot open load file: sx-search```
with sx version .3, or 20150511.931, with ```M-x sx-search``` or the search hotkey in an sx buffer.

Still on Emacs 24.3 because that's what's available in the Ubuntu 14.04 repo, if that's relevant.

Great package by the way!

**Comment by Malabarba** [comment]
@peterbecich could you open a new issue for this? I think it's a separate issue. 
Also, could you try reinstalling the package? That sounds like it may be a faulty installation.

**Comment by peterbecich** [comment]
Thanks!  I had reinstalled the package, but restarting Emacs was necessary to get it working.
