### ISSUE TITLE
 sx--maybe-site-prompt is needed by sx-search

### ISSUE THREAD

**Issue by thomasf** [vermiculus/sx.el#284]
sx--maybe-site-prompt has to be added to the autoloads or explicitly required somewhere.

**Comment by thomasf** [comment]
Seems to be lot's of other auto loads missing as well?

**Comment by thomasf** [comment]
I see, there is a sx-load.. An immediate fix would be to require that one somwhere?

**Comment by vermiculus** [comment]
Yes, you're correct that `(require 'sx-load)` is the workaround for this at the moment. I've still got to work out the dependency DAG (hopefully it's a DAG…) so autoloads and requires are still a little… wonky.

**Comment by Malabarba** [comment]
Yes, `sx-load` is a convenience we offer to the users, but it's just a crutch. Please report any such inconsistencies you find.
In this case it was a missing require.

**Comment by Malabarba** [comment]
Yes, `sx-load` is a convenience we offer to the users, but it's just a crutch. Please report any such inconsistencies you find.
In this case it was a missing require.
