### ISSUE TITLE
Add specific key face for headers

### ISSUE THREAD

**Issue by thomasf** [vermiculus/sx.el#285]
Trying to implement a good solarized-theme matching other modes:

If you add a generic key face, author can use that.. Or add an author face if that works for you.

Compare to (mu4e) message mode:

![image](https://cloud.githubusercontent.com/assets/330847/7250104/aed05f92-e81f-11e4-8272-05212ffc375f.png)

**Comment by vermiculus** [comment]
What exactly do you mean by 'generic key face'? In the above screenshot, which pieces of text would count as such?

**Comment by thomasf** [comment]
The user name has the same color as  "Author: " label which is not true for all other lines.

**Comment by vermiculus** [comment]
[Region of interest.](https://github.com/vermiculus/sx.el/blob/50a064f5e1ec85765ab0670cd2a04d2499f6cf65/sx-question-print.el#L310-314)

**Comment by vermiculus** [comment]
A `describe-face` on the author yields the header face – something has certainly changed since the screenshot posted.

**Comment by thomasf** [comment]
Hmm. I installed sx from melpa today.

**Comment by vermiculus** [comment]
Oh, no, that's not what I meant :) I mean the screenshot is out-of-date -- it displays the correct behavior, whereas the correct behavior is no longer exemplified in the actual code.

**Comment by Malabarba** [comment]
Thanks @thomasf, that was a bug. The sx-user-name face wasn't getting used.
Since you're theming, other user-related faces to keep in mind are `sx-user-reputation` and `sx-user-accept-rate` (this last one isn't used ATM but probably will in the future).

**Comment by thomasf** [comment]
Thanks for the information
