### ISSUE TITLE
 Cannot open load file: sx-search

### ISSUE THREAD

**Issue by peterbecich** [vermiculus/sx.el#289]
I get ```execute-extended-command: Cannot open load file: sx-search```
with sx version .3, or 20150511.931, with ```M-x sx-search``` or the search hotkey in an sx buffer.

Still on Emacs 24.3 because that's what's available in the Ubuntu 14.04 repo, if that's relevant.

Great package by the way!

------------------------------------

Fixed by reinstalling package and restarting Emacs!  Previously had only reinstalled package, and this did not fix it.  I didn't know that the package menu required any Emacs restarts.

**Comment by Malabarba** [comment]
No problem, glad it's solved.
