### ISSUE TITLE
There should be a short usage section

### ISSUE THREAD

**Issue by tuhdo** [vermiculus/sx.el#291]
I think even a link to [this article from](http://endlessparentheses.com/sx-el-announcement-and-more-launcher-map.html) from @Malabarba would be very useful.

**Comment by tuhdo** [comment]
What I really mean is that there should be sample configuration with premade key bindings to all frequently used commands, so users can easily copy and try the package and later modify the keys.

**Comment by tuhdo** [comment]
`w` should be mentioned that it could copy code from answer to the mark ring. This is an extremely feature imo.

**Comment by Malabarba** [comment]
Yeah, we could suggest a keymap on the readme. More importantly, we need an entire Readme section about the question buffer, then we could mention the w key.
Any volunteers? =)

**Comment by vermiculus** [comment]
[I volunteer!](http://i.giphy.com/lu5LYc87R1960.gif)

**Comment by Malabarba** [comment]
:+1:

**Comment by vermiculus** [comment]
@tuhdo @Malabarba Anything you'd add to the above?

**Comment by tuhdo** [comment]
There should be a sample Elisp configuration with key bindings. That way, people can quickly copy/paste and try out `sx`, without the hassle of writing the boilerplate themselves.

**Comment by vermiculus** [comment]
I'm not sure what key-bindings are necessary beyond the default. Can you share your configuration? (Ironically, I don't get to use this much – my work computer can't manage the `url` business.)

**Comment by tuhdo** [comment]
Key bindings that enable us to enter `sx` to use the rest of default key bindings. The key bindings specified in @Malabarba's [article](http://endlessparentheses.com/sx-el-announcement-and-more-launcher-map.html) is a good example.

**Comment by vermiculus** [comment]
@tuhdo Ah! I never thought about those commands :) Smex/flx-ido have spoiled me :) Is everyone satisfied with the above? Any more ideas/things to add?

**Comment by Malabarba** [comment]
I like both commits. It occurs to be now that we should mention `sx-search` in with the entry commands as well.
Besides this, and the comments I made on the commit, I'm good with merging.

Thanks Sean

**Comment by tuhdo** [comment]
Look perfect now. I have no further idea.
