### ISSUE TITLE
sx search results more restricted than browser's search results

### ISSUE THREAD

**Issue by peterbecich** [vermiculus/sx.el#296]
Some search queries in sx Search yield fewer results than the same query on a Stack Exchange site.

For example, I'll search for a question titled "improve doc-view display quality" on the Emacs Stack Exchange site:
http://emacs.stackexchange.com/questions/876/improve-doc-view-display-quality

The query "doc-view quality" yields no results in sx, but same query yields the question in the browser:
http://emacs.stackexchange.com/search?q=doc-view+quality

The query "doc-view display" in sx yields the question:
```   5   1 improve doc-view display quality       9mo ago [pdf] [docview]                                  wdkrnls  938 ```

Is the regex parser of sx queries more restricted than the one in the browser?

**Comment by Malabarba** [comment]
Unfortunately, that's a limitation of the stack exchange. API. =/ Last I checked, it only supports one form of searching, which is by strict substring.
That's why `doc-view display` finds the question, whereas `doc-view quality` doesn't. The first is a strick substring, whereas the second is a fuzzier match.

**Comment by Malabarba** [comment]
[Quoting the doc](https://api.stackexchange.com/docs/search):

> This method is intentionally quite limited. For more general searching, you should use a proper internet search engine restricted to the domain of the site in question.

**Comment by vermiculus** [comment]
Still, a less-specific search could be made via API and the restriction made clientside. It's a gross solution (and it shouldn't have to work like this) but it is possible.

**Comment by Malabarba** [comment]
Hmm. Good point. We could make one search for each word, and then take the intersection.

**Comment by peterbecich** [comment]
I see.
The intentional limitation makes some sense.  Many sites mirror and crawl Stack Exchange, and maybe this limited search API saves a little processing:  http://meta.stackexchange.com/questions/131846/report-sites-that-use-stack-exchange-content-without-following-attribution-rules

**Comment by vermiculus** [comment]
I was thinking more along the lines of
1. Search for *foo*.
2. Search (search results for *foo*) for *bar*.
Fewer API calls.

**Comment by Malabarba** [comment]
Indeed, I think I like your version better.

**Comment by Malabarba** [comment]
Oh wait. It's a whoooole lot simpler than this. There's a `search/advanced` method that does what we want! :)

**Comment by vermiculus** [comment]
*Woah!*

**Comment by peterbecich** [comment]
Cool!  Makes a big difference!  Thanks.
