### ISSUE TITLE
speed up opening question

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/sx.el#305]
I found sx.el will write question id to file `read-questions.el`. I know sx.el need a mechanism to mark question read status. But I found it is slow for opening question. I don't know whether slow on this. I don't know how to profile this. (Maybe network transfer time spent)
Or make it async?
If it is fast after profile, please ignore this issue.

**Comment by Malabarba** [comment]
How slow is it for you?
Could you give us a link to a question which is slow to open?

Most likely this slowness is in the network transfer.

**Comment by stardiviner** [comment]
About 3 ~ 5 seconds. Not on specific question.
Me too. I thought mostly could be network transfer problem. (Still take an ask :smile: )

**Comment by Malabarba** [comment]
Try using the profiler. 

1. M-x profiler-start 
2. Visit a question. 
3. M-x profiler-report

**Comment by stardiviner** [comment]
I rebooted my system, now, it's faster now.
And I did profiler, not heavy. I'll close it now.
