### ISSUE TITLE
support for add code block with stack exchange format in markdown edit buffer

### ISSUE THREAD

**Issue by stardiviner** [vermiculus/sx.el#306]
I write answer with code block, but it does not have newline.
Here is the screenshot of result.

![sx el answer block issue 1](https://cloud.githubusercontent.com/assets/378699/10563732/610de3ce-75c8-11e5-8ce6-0fa541c3f550.png)

**Comment by Malabarba** [comment]
Oh, I was under the impression that tripple backticks weren't valid code-blocks in SX format.

**Comment by stardiviner** [comment]
Oh, right. I forgot is. I will create a snippet by myself.
close it now.
