### ISSUE TITLE
<hr/> elements break tag rendering?

### ISSUE THREAD

**Issue by phil-s** [vermiculus/sx.el#307]
I noticed that some but not all of the `kbd` tags are handled by `sx` for this answer: http://emacs.stackexchange.com/questions/17386/display-all-setq-possibilities/17433#17433

I also noticed that the first `<hr/>` is hidden, and the subsequent ones appear as HTML.

My guess is that the initial `<hr/>` is breaking everything following it.

**Comment by Malabarba** [comment]
Yes, your assessment looks correct.
I'll try to fix it next week.

**Comment by phil-s** [comment]
Thank you, that's looking good now.
