### ISSUE TITLE
Can not see acces token

### ISSUE THREAD

**Issue by anquegi** [vermiculus/sx.el#316]
When I start with sx-authenticate, it opens this view, and I cannot do anything, what should I do, Where to get that token, is emacs 25.1 on Mac

<img width="1280" alt="screen shot 2016-02-24 at 19 23 01" src="https://cloud.githubusercontent.com/assets/2518346/13296086/0c3193b8-db2c-11e5-8a52-a6093ffdde72.png">

<img width="1280" alt="screen shot 2016-02-24 at 19 19 58" src="https://cloud.githubusercontent.com/assets/2518346/13296043/e73c64b6-db2b-11e5-9345-75de8e29588c.png">

**Comment by vermiculus** [comment]
Does eww have a javascript engine?

**Comment by anquegi** [comment]
Hi, Thanks for your answer, I need to activate this javascript engine, How can I do it, I'm not sure if I need to configurate something else in emacs

Thanks for your help

**Comment by Malabarba** [comment]
No, eww does not do javascript. You'll have to switch to an external browser for the authentication.

**Comment by anquegi** [comment]
But how can I switch to an external browser, and why the mode is opening eww instead of the external browser. Sorry for not Knowing this things

**Comment by Malabarba** [comment]
SX simply calls `browse-url` to open that page which invokes your default browser.

If you didn't configure eww as your default browser in emacs, then Emacs must be using eww because it couldn't find any other browsers. Sadly, I have no experience with Emacs on MacOS, so I can't help you there.

**Comment by vermiculus** [comment]
I can confirm `browse-url` works on OS X. It looks like you use Firefox, so (by default) emacs will open it up in Firefox. I would look at customizing `browse-url-browser-function`.

**Comment by anquegi** [comment]
Yes, I use firefox that's true I also try this configurations but nothing else happens:

1)
(setq browse-url-browser-function 'browse-url-default-macosx-browser)

2)
(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "firefox")
3)
(setq browse-url-browser-function 'browse-url-firefox)
  (setq browse-url-firefox-program 
"/Applications/Firefox.app/Contents/MacOS/firefox")

4)
(setq browse-url-browser-function 'browse-url-generic
      browse-url-generic-program "chromium-browser")

**Comment by anquegi** [comment]
Hi, I finally get it working, I followed this answer http://stackoverflow.com/questions/4506249/how-to-make-emacs-org-mode-open-links-to-sites-in-google-chrome for setting the default mac os browser, finally this opens the page in the firefox and it works. Thanks a lot for your suport without your previous comment about browse-url. I will never figure how to solve this problem

**Comment by Malabarba** [comment]
Great! ☺
