### ISSUE TITLE
Hi, why my sx-search returns all japanese questions

### ISSUE THREAD

**Issue by cmal** [vermiculus/sx.el#321]
what I actually want is English questions and answers. I don't recognize any Japanese words at all. Is this a problem of the api of stackexchange?
Can I tweek sx to make it return English results?
thanks!

**Comment by vermiculus** [comment]
That's… a new one. There's absolutely zero handling in sx.el for different languages – can you provide an example?

**Comment by cmal** [comment]
😄  I'm sorry. I've found that I searched the ja.stackoverflow . and it certainly returns japanese answers. 😆

**Comment by vermiculus** [comment]
😉
