### ISSUE TITLE
sx-open-link does not work with browse-url-browser-function

### ISSUE THREAD

**Issue by jabranham** [vermiculus/sx.el#323]
I'm trying to get it set up to where if I open a stackexchange link in Emacs it uses sx.el instead of firefox or eww or whatever. I currently have this:

```emacs-lisp
(push '(".*stackexchange.*" . sx-open-link) browse-url-browser-function)
```

In my config. But when I do C-c C-o on a link to follow it, I get this error:

```
apply: Wrong number of arguments: (1 . 1), 2
```

If I do `M-x sx-open-link` and yank the link in, everything works great.

**Comment by vermiculus** [comment]
What are the arguments being passed to it? The error means that `sx-open-link` takes exactly one mandatory argument, but it was passed two arguments.

**Comment by jabranham** [comment]
Wow, that was fast. Thanks!

**Comment by Andre0991** [comment]
I'm late to the party, but here's an useful customisation: if possible, open SE links from `eww` using `sx.el`:

```
(defun andre-eww-follow-link-maybe-sx (orig-fun &rest args)
  (let ((url (get-text-property (point) 'shr-url)))
    (if (or
         (string-match ".*\.stackexchange\.com" url)
         (string-match ".*\.stackoverflow\.com" url))
        (sx-open-link url)
      (apply orig-fun args))))

(advice-add 'eww-follow-link :around #'andre-eww-follow-link-maybe-sx)
```

**Comment by vermiculus** [comment]
I'm surprised eww doesn't use `browse-url`.
