### ISSUE TITLE
Error with Org 9.0: "Symbol's value as variable is void: org-store-link-functions"

### ISSUE THREAD

**Issue by xuchunyang** [vermiculus/sx.el#324]
> a description of what you are trying to do

`M-x sx-tab-newest`

> the behavior you actually see

It doesn't work by reporting

    eval-after-load: Symbol's value as variable is void: org-store-link-functions

in the message buffer.

> steps we can take to reproduce the bug

Upgrade to org-mode 9.0 then `M-x sb-tab-newest`. The version I am using are:

- sx version 20161104.1755 from Melpa
- Org mode version 9.0 (release_9.0 @ /home/xcy/src/org-mode/lisp/)

---
https://github.com/vermiculus/sx.el/blob/87dfd1e2ce093d53c0919dac7899bbf06bd96224/sx-interaction.el#L230-L231 has

```
(eval-after-load "org"
  '(add-to-list 'org-store-link-functions #'sx-org-get-link))
```

but I don't find the `org-store-link-functions` variable in org 9.0 and it looks like be removed by [this commit](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=commit;h=9bc294003417a17c58b1c25156a885b5ac109309).

**Comment by vermiculus** [comment]
Confirmed; I can work on this tonight.

**Comment by vermiculus** [comment]
How does the above work for you?

**Comment by xuchunyang** [comment]
It works good: previous error is gone and `org-store-link` works like expected. I apply your patch and re-byte-compile `sx-interaction.el`.
