### ISSUE TITLE
show math formule

### ISSUE THREAD

**Issue by songpeng** [vermiculus/sx.el#331]
Hi, 
when I enter the math topic, latex format is the original one. How can I make it possible to see the real formula?
Thanks
Songpeng

**Comment by vermiculus** [comment]
Similar to AUCTeX's `preview-latex`? I'm afraid that's not yet possible. Pull requests are welcome, though 😉

**Comment by TobiasZawada** [comment]
That works out of the box with https://github.com/TobiasZawada/TeXfrag/. It would be nice if `sx-question-mode--print-question` would run a hook after printing is finished. Therewith I wouldn't need to advice `sx-question-mode--print-question`.

**Comment by TobiasZawada** [comment]
@vermiculus May I insert additional newlines into the print buffer after `sx-question-mode--print-question` has finished?

**Comment by vermiculus** [comment]
I agree that trying to correct bad formatting on account of display-math being inline in a paragraph is out-of-scope for this; I don't think MathJax knows how to 'continue' a paragraph as TeX does after `$$` or `\[` anyway.

A hook seems like a fantastic idea; would you mind opening a PR? 😄

**Comment by TobiasZawada** [comment]
The last version of [TeXfrag](https://github.com/TobiasZawada/TeXfrag) fixes the display-math problem. It inserts missing newlines around display-math environments.

**Comment by vermiculus** [comment]
Thanks again for the PR 😄 should we consider this issue resolved, or is there more we can do to advertise the capability of this combo?

**Comment by TobiasZawada** [comment]
You wrote: 
> Thanks again for the PR :smile: should we consider this issue resolved, or is there more we can do to advertise the capability of this combo?

I regard this issue as resolved if https://travis-ci.org/vermiculus/sx.el/builds/321518650?utm_source=github_status&utm_medium=notification is nothing serious.
Could you tell me what the failing of that test means and how serious it is?

Note: I wrote TeXfrag for other use-cases (e.g., showing math in doxygen comments and showing math of html pages with embedded MathJax in eww).
When I saw sx I noted that TeXfrag can also be helpful there. I think if you use it for sx it should become part of elpa?

**Comment by vermiculus** [comment]
The tests are failing because ~~we've neglected to update them after some fairly core markdown-mode changes~~ our entire testing framework is temporarily broken, probably related to cask-path issues. They're nothing to worry about. The big thing we care about is whether it compiles without errors – ideally without warnings.

If you submit it to the ELPA, that would likely be a boon for the entire Emacs community – but you will need to provide copyright assignment to the FSF. Submitting to MELPA will achieve almost the same effect (and it's worthwhile to note that sx.el itself is also excluded from the ELPA).

**Comment by TobiasZawada** [comment]
Of course, melpa it is. Somebody already has put msearch.el into melpa. I never did something like that myself before. Okay time to learn something new...

**Comment by songpeng** [comment]
@vermiculus @TobiasZawada 
hi, guys,
thanks a lot for your efforts, and I test it in math stack exchange. It works well! I love it.
Just one small question, is it possible to set  textfrag always show the preview under the math stack exchange?
Songpeng

**Comment by songpeng** [comment]
wait, I just set the texfrag global mode. and it works automatically to detect the latex fragment. 
Thanks!
