### ISSUE TITLE
Crash on sx-open-link

### ISSUE THREAD

**Issue by impaktor** [vermiculus/sx.el#332]
When I visit: 
https://stackoverflow.com/questions/29954263/what-does-the-term-broadcasting-mean-in-pandas-documentation

by calling `sx-open-link` Emacs crashes. 

I'm running GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16, from Arch Linux.

**Comment by vermiculus** [comment]
Do you have any sort of backtrace?

**Comment by vermiculus** [comment]
Also, is 25.3 even stable yet?

**Comment by impaktor** [comment]
> Do you have any sort of backtrace?

Nope, nothing from lisp/within emacs, as it dies pretty hard. Dunno if it's compiled with `-g -O0` and if gdb would turn somthing out. Currently not able to test. I assume you're unable to reproduce?

> Also, is 25.3 even stable yet?

I don't use "experimental" / "testing" repos. It's from September. As far as I know, the second release candidate for Emacs 26 was recently released, so this isn't that much of "bleeding edge".

**Comment by vermiculus** [comment]
Wow, time really has flown by.  I'll give it a shot and see what I can figure out -- thanks for the report!

**Comment by vermiculus** [comment]
(Ah, 25.3 was the security fix. I remember that now.)

**Comment by vermiculus** [comment]
Confirmed 25.2 on OS X not affected :frown:

**Comment by vermiculus** [comment]
And confirmed 25.3 on OS X not affected.

I don't suppose you have a Vagrant file for your setup, do you? :frowning:

**Comment by impaktor** [comment]
I've had a similar crash on opening a wiki page in eww, also just now following a png-file, C-x C-f, so common denominator in all three cases were that Emacs should display an image and then kills itself.

I'm a bit stumped, as Emacs should't crash like this. Almost like there's something fundamentally amiss with the universe. Anyway, I then suggest it's not an sx thing, but rather a emacs-displaying-images-thing.

**Comment by vermiculus** [comment]
Yeah, that makes more sense :-( I'm sorry this is broken for you.  I'm going to close this issue since there's no follow-up to be done here.

Did you submit a bug report?

**Comment by impaktor** [comment]
> I'm going to close this issue since there's no follow-up to be done here.

Yeah, makes sense.

> Did you submit a bug report?

Nope. I might ask in #emacs
