### ISSUE TITLE
How to remap keys for `sx-question-list-mode`

### ISSUE THREAD

**Issue by ztlevi** [vermiculus/sx.el#333]
I'm trying to remap keys for `sx-question-list-mode`, but it's not working.

Here is the code I'm using.
```
    (with-eval-after-load 'sx-question-list-mode
      (progn
        (define-key sx-question-list-mode-map "j" 'sx-question-list-next)
        (define-key sx-question-list-mode-map "k" 'sx-question-list-previous)
        ))
```

This actually works if I evaluate the `define-key` manually by `C-x C-e` after `sx-question-list-mode` enabled.

Does anyone what's going on here?

Thanks~

**Comment by vermiculus** [comment]
The feature name is `sx-question-list`, not `sx-question-list-mode` :-)

**Comment by ztlevi** [comment]
Oh, that's right. Thanks!
