### ISSUE TITLE
sx-inbox-notifications error "Wrong type argument: stringp, nil"

### ISSUE THREAD

**Issue by Boruch-Baum** [vermiculus/sx.el#339]
I'm able to evaluate function `sx-inbox`, but evaluating function `sx-inbox-notifications` yields "Wrong type argument: stringp, nil". The same result occurs when trying the default keybinding `C-u s i`.

On the other hand, manually evaluating `(sx-method-call 'notifications)` DOES return a lisp object containing notifications.

@Malabarba, I noticed from issue / pull request #174 that you originally contributed this code, so I'm mentioning you to get your attention.

I'm using emacs version 25.2 in debian, and `sx.el` otherwise functions fine, allowing me to submit questions, answers, votes and comments.

The \*Messages\* buffer indicates that the error is being generated by function `sx-inbox--print-info`.

**Comment by Boruch-Baum** [comment]
Fixed in my pull request #343.

**Comment by vermiculus** [comment]
Closing after merge.
